name: easypdf
description: "EasyPDF - Convert images to PDF quickly and easily."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6

  # Firebase
  firebase_core: ^3.6.0
  firebase_auth: ^5.7.0
  cloud_firestore: ^5.6.12
  google_sign_in: 6.2.1

  # State management
  provider: ^6.1.2

  # Image capture & processing
  camera: ^0.11.0+2
  image_picker: ^1.1.2
  edge_detection: ^1.0.6
  image: ^4.2.0

  # PDF
  pdf: ^3.11.1
  printing: ^5.13.3

  # Storage / sharing
  path_provider: ^2.1.4
  share_plus: ^10.0.2
  permission_handler: ^11.3.1

  # UX
  smooth_page_indicator: ^1.2.0+3
  google_fonts: ^6.2.1
  firebase_database: ^11.3.10
  mailer: ^7.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  # assets:
  #   - assets/images/
